//! Tauri build-script hook: icon/resource embedding, platform metadata,
//! and conditionally writing the E2E-only WebDriver capability file (see
//! `src/lib.rs`'s `register_e2e_plugins` and `docs/gui-testing.md`).
//!
//! `tauri-plugin-wdio` and `tauri-plugin-wdio-webdriver` require
//! `wdio:default`/`wdio-webdriver:default` capability entries to function,
//! but referencing those permissions when the plugins aren't linked in
//! (i.e. the `e2e-webdriver` feature is off) fails Tauri's build-time ACL
//! resolution outright. So these capabilities live in their own file that
//! only exists on disk while building with that feature enabled; every
//! default/production build removes it if present.

use std::fs;
use std::path::Path;

const E2E_CAPABILITY_PATH: &str = "capabilities/e2e-webdriver.json";
const E2E_CAPABILITY_CONTENTS: &str = r#"{
  "$schema": "../gen/schemas/desktop-schema.json",
  "identifier": "e2e-webdriver",
  "description": "Capability for tauri-plugin-wdio's execute/mocking API and tauri-plugin-wdio-webdriver's embedded WebDriver server. Generated by build.rs only when the e2e-webdriver Cargo feature is enabled; absent from every default/production build.",
  "windows": ["main"],
  "permissions": ["wdio:default", "wdio-webdriver:default"]
}
"#;

/// Writes or removes `capabilities/e2e-webdriver.json` to match whether the
/// `e2e-webdriver` feature is enabled for this build.
fn sync_e2e_capability_file() {
    let path = Path::new(E2E_CAPABILITY_PATH);
    let feature_enabled = std::env::var_os("CARGO_FEATURE_E2E_WEBDRIVER").is_some();

    if feature_enabled {
        if let Err(err) = fs::write(path, E2E_CAPABILITY_CONTENTS) {
            println!("cargo:warning=failed to write {E2E_CAPABILITY_PATH}: {err}");
            std::process::exit(1);
        }
    } else if path.exists() {
        if let Err(err) = fs::remove_file(path) {
            println!("cargo:warning=failed to remove stale {E2E_CAPABILITY_PATH}: {err}");
            std::process::exit(1);
        }
    }
}

fn main() {
    sync_e2e_capability_file();
    tauri_build::build()
}
